### ISSUE TITLE
data.id is returning null

### ISSUE THREAD

**Issue by rishav00a** [Flutterwave/flutterwave-flutter#18]
As per documentation, we can verify payment by data.id, but when we get the response from Flutter plugin, it is retuning null in data.id, how to verify the payment ?

    {
        status: success,	
        message: Transaction fetched successfully,	
        data: {
		id: null,
		tx_ref: My_unique_transaction_reference_12345,
		flw_ref: flwm3s4m0c1604002887784,
		device_fingerprint: null,
		amount: 200,
		charged_amount: 200,
		app_fee: 5,
		merchant_fee: 0,
		processor_response: Approved,
		auth_model: MOBILEMONEY,
		currency: GHS,
		ip: ::ffff: 10.45 .226 .51,
		narration: FLUTTERWAVE V3 DOCS,
		status: successful,
		auth_url: null,
		payment_type: mobilemoneygh,
		fraud_status: null,
		payment_code: null,
		charge_type: null,
		created_at: null,
		account_id: null,
		customer: {
			id: 510307,
			phone_number: 0123456789,
			name: Valid Full,
			email: valid @email.com,
			created_at: 2020 - 10 - 20 T19: 46: 05.000 Z
		}
	}
    }

**Comment by FredDominant** [comment]
Hello @rishav00a, thank you for reaching out. Do you still experience this?

**Comment by haybankz** [comment]
Hi, I'm also experiencing this, i'm currently on debug mode

**Comment by rishav00a** [comment]
You can go for Webhook, i did the same.
