### ISSUE TITLE
Loading dialog show forever

### ISSUE THREAD

**Issue by Keithwachira** [Flutterwave/flutterwave-flutter#23]
After initializing a payment ,the loading dialog never stop showing it loads forever.

**Comment by FredDominant** [comment]
Hi @Keithwachira, thank you for reaching out. Does this happen when you try to charge a card?

**Comment by Keithwachira** [comment]
Hello @FredDominant it happens when using Mpesa option

**Comment by FredDominant** [comment]
Thank you, @Keithwachira, this is being looked at.

**Comment by Keithwachira** [comment]
In the meantime i am not sure what i should use.

**Comment by FredDominant** [comment]
Hi @Keithwachira , please join us here `https://join.slack.com/t/flutterwavedevelopers/shared_invite/zt-7mdxu82t-~WwizwN3eWKjUXLY275AzQ`, so we can have more context about the issue.

**Comment by FredDominant** [comment]
Hello @Keithwachira

**Comment by FredDominant** [comment]
Hello @Keithwachira, we're unable to replicate this issue while paying with Mpesa. Could you share steps to replicate so we can fix?

**Comment by Keithwachira** [comment]
Hello,
Thank you for the quick reply....Try Mpesa with an account that has insufficient balance.(That is when an Mpesa transaction fails).

**Comment by Keithwachira** [comment]
@FredDominant  am not sure if you are using the progress_dialog package but i think it is the issue.After upgrading flutter I realized calling await pr.hide() does not hide the progress dialog .
