### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by odejinmi** [Flutterwave/flutterwave-flutter#24]
when I initialize rave this is the error I get, please help, Thanks in advance
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_svg-0.13.1/lib/src/picture_stream.dart:92:3: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
  PictureStream();
  ^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_svg-0.13.1/lib/src/picture_stream.dart:192:16: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
abstract class PictureStreamCompleter extends Diagnosticable {
               ^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/dio-2.2.2/lib/src/dio_http_headers.dart:55:8: Error: The method 'DioHttpHeaders.add' has fewer named arguments than those of overridden method 'HttpHeaders.add'.
  void add(String name, value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:699:8: Context: This is the overridden method ('add').
  void add(String name, Object value,
       ^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/dio-2.2.2/lib/src/dio_http_headers.dart:70:8: Error: The method 'DioHttpHeaders.set' has fewer named arguments than those of overridden method 'HttpHeaders.set'.
  void set(String name, Object value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:708:8: Context: This is the overridden method ('set').
  void set(String name, Object value,
       ^

**Comment by FredDominant** [comment]
@odejinmi, thank you reaching out. The team is looking into this.

**Comment by odejinmi** [comment]
@FredDominant, I'm still waiting for your response

**Comment by FredDominant** [comment]
Hello @odejinmi, please check that you're adding no dependency that requires `flutter_svg` because the SDK doesn't use this library/dependency. And if you are, you can update it in your `pubspec.yml` file

**Comment by odejinmi** [comment]
Hi @FredDominant, I did not use flutter_svg package, these are the packages I use :-
cupertino_icons:
  lottie:
  responsive_framework:
  shared_preferences:
  firebase_core:
#  firebase_auth:
  firebase_storage:
  firebase_database:
  local_auth:
  google_sign_in:
  flutter_facebook_login:
  device_info:
  http:
  cached_network_image:
  fluttertoast:
  package_info:
  flutter_paystack:
  flutter_rave:
  contact_picker:
  flutter_tts:
  adsunity:
  ads:
  device_apps:
  random_string:
  rate_my_app:
  flutter_email_sender:
  firebase_dynamic_links:
  share:
  file_picker:
![image](https://user-images.githubusercontent.com/45696129/103433843-2fe69c80-4bad-11eb-801c-f923c1e52c20.png)

**Comment by odejinmi** [comment]
I just created a new project with no other dependency apart from flutterwave and I am having the same error

**Comment by FredDominant** [comment]
Hi @odejinmi, thank you for reaching out. The team has been unable to replicate this. 

You could try the following steps:
1. run `flutter clean`
2. Add the latest version of `flutter_svg` in your `pubsepc.yaml` file.
3. If you're using Android Studio, Invalidate cache and restart your Android Studio.

**Comment by FredDominant** [comment]
@odejinmi, have you tried the steps above?
