### ISSUE TITLE
Plugin Doesn't work properly

### ISSUE THREAD

**Issue by yalzeee** [Flutterwave/flutterwave-flutter#25]
When I follow up with a test card it show transaction fetched successfully and doesn't return anything to the flutter card. So I tried again with wrong pins and it opened a web view and succeeded with the wrong pin and otp. Don't know how that is possible. Don't think this plugin is production ready

**Comment by FredDominant** [comment]
Hello @yalzeee, thank you for reaching out. Can you please explain more on what you mean by it doesn't return anything to the flutter card. And also, what test card did you use. Please note that the card validations and PIN authorisations are mocked on staging on the backend.

**Comment by princesegzy01** [comment]
I am also getting same error "transaction fetched successfully" without knowing if it is successful or not on the flutter side.

I also got some database error earlier when I was doing some test on it.

**Comment by FredDominant** [comment]
Hi @princesegzy01, thank you for reaching out. Please post the final result you get from the transaction so we investigate further.

**Comment by princesegzy01** [comment]
@FredDominant like I said above.. After you have input the test card and it Is been verified. It will output "transaction fetched successfully". This doesn't indicate if the transaction is successful or not.

But I still get emails of successful transaction. The problem is on the plugin side to output the correct response after a card is charged

**Comment by FredDominant** [comment]
@princesegzy01, I'm assuming you get toast with that message. After the toast is displayed, does the Flutterwave payment screen close and return you to previous page?

If it does, then following the documentation, you should get an instance of `ChargeResponse` when the transaction completes. With this instance, you get the status of the transaction and other information you need.

Please see a sample implementation [here](https://github.com/Flutterwave/flutterwave-flutter#1-create-a-flutterwave-instance)
