### ISSUE TITLE
data.id is returning null

### ISSUE THREAD

**Issue by haybankz** [Flutterwave/flutterwave-flutter#26]
I made a successful payment on the test mode. Here is the charge response:
{status: success, 
message: Transaction fetched successfully, 
data: {id: null, 
tx_ref: 0001, flw_ref: FLW-MOCK-912fd276f678a0419f71cbc763a0804b, device_fingerprint: null, amount: 1000, charged_amount: 1000, app_fee: 14, merchant_fee: 0, processor_response: successful, auth_model: PIN, currency: NGN, ip: ::ffff:10.45.47.90, narration: CARD Transaction , status: successful, auth_url: null, payment_type: card, fraud_status: null, payment_code: null, charge_type: null, created_at: null, account_id: null, 
customer: {
id: 546219, 
phone_number: N/A, 
name: Oladele Name, 
email: koleson.legen@extraale.com, 
created_at: 2020-12-15T05:31:40.000Z
}
}
}

**Comment by FredDominant** [comment]
Hello @haybankz, thank you for reaching out. Could you share the test card details you used when experiencing this, so the team can reproduce and fix.

**Comment by haybankz** [comment]
Hi @FredDominant, i used this card.
Card number: 5531 8866 5214 2950
cvv: 564
Expiry: 09/32
Pin: 3310
OTP: 12345

**Comment by codefalcon95** [comment]
Hello @FredDominant can we get a feedback , also experiencing this at our organization here, the package using version 3 api, doesnt return the needed transaction id (Id)

**Comment by FredDominant** [comment]
@codefalcon95, @haybankz, this is being resolved on the backend and should be in production soon.

**Comment by haybankz** [comment]
Thank you @FredDominant , please do well to inform us when it's in production..thanks

**Comment by FredDominant** [comment]
Hello @haybankz, @codefalcon95. This has been fixed. Please confirm.

**Comment by FredDominant** [comment]
@haybankz, @codefalcon95, closing this now.

**Comment by codefalcon95** [comment]
Hello @FredDominant yeah, thanks it has been fixed
