### ISSUE TITLE
plugin UI

### ISSUE THREAD

**Issue by mimigithub-prog** [Flutterwave/flutterwave-flutter#27]
Can you please work on your UI to look more nice , and make it customizable

**Comment by FredDominant** [comment]
Hello @mimigithub-prog, this is already in the works. Thank you for reaching out.

**Comment by TJMusiitwa** [comment]
I would like to add my voice to this issue, where if possible,use a SafeArea widget as the parent for the body widget such that we may avoid instances of system User interfaces causing a slight issue with the ui as given in the example here on iOS.

![Screenshot 2021-02-14 at 19 07 31](https://user-images.githubusercontent.com/28179360/107886521-35e3d300-6ef8-11eb-8a60-5a5ee38dce63.png)
