### ISSUE TITLE
payment has no option to go back to previous screen on iOS

### ISSUE THREAD

**Issue by Saintiano** [Flutterwave/flutterwave-flutter#28]
payment has no option to go back to previous screen on iOS and the debug badge keeps showing despite setting isDebug false

**Comment by flamezbaba** [comment]
i am having the same issue

**Comment by FredDominant** [comment]
Hello @flamezbaba, @Saintiano Thank you for reaching out. This has been fixed in the latest update `https://pub.dev/packages/flutterwave/versions/0.0.3-dev.1`

**Comment by Saintiano** [comment]
Dear Adewole,

Thanks

I will look at it

Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
