### ISSUE TITLE
No Support for ZAR Currency

### ISSUE THREAD

**Issue by Ndivhuwo** [Flutterwave/flutterwave-flutter#30]
When are the other currencies available? When is v3 coming out. We love Flutterwave in SA, and would like to use it soon please.

**Comment by FredDominant** [comment]
Hi @Ndivhuwo, thank you for reaching out. This would be made available soon.

**Comment by Ndivhuwo** [comment]
Thanks for the feedback @FredDominant . Do you have an estimated date on the availability please?

**Comment by FredDominant** [comment]
Hello @Ndivhuwo, this is currently in the works, and should released soon. Thank you for using Flutterwave.
