### ISSUE TITLE
payments into European Bank accounts

### ISSUE THREAD

**Issue by joe-getcouragenow** [Flutterwave/flutterwave-flutter#32]
I need the ability for Africans to pay into our Euro bank using a Payment Link. https://developer.flutterwave.com/docs/payment-links

All i saw was this:https://github.com/Flutterwave/flutterwave-flutter/blob/development/lib/core/flutterwave.dart#L71

Is this currently possible ?

**Comment by FredDominant** [comment]
Hi @joe-getcouragenow thank you for reaching out. This is not possible on the Flutter package.
