### ISSUE TITLE
Returns null on continue then shows initiating payment forever

### ISSUE THREAD

**Issue by musukwamoshi** [Flutterwave/flutterwave-flutter#33]
I'm trying to test your flutter package using your mastercard/visa  test cards. When I click pay, it returns a no response message(null result) without any cancellation from user ,then shows the initiating payment dialog forever. Package version is 0.0.2.What could be the problem?

**Comment by FredDominant** [comment]
Hello @musukwamoshi, thank you for reaching out. Could you reply with the test card details and steps to recreate this error?  Thank you.
