### ISSUE TITLE
Unable to change phone number on mobile money payment screen.

### ISSUE THREAD

**Issue by djoks** [Flutterwave/flutterwave-flutter#34]
The plugin seems to require the phone number of the customer at the time of initialisation.  The problem is users don't always pay with the numbers they registered with in a lot of apps.

Your mobile money payment page displays a 3 fields, one for the phone number, one for the voucher and the other for the network.

Ignoring the UI can you please make it so that the phone number passed can be changed on that page?

My users have already started complaining about it.

**Comment by FredDominant** [comment]
Hi @djoks , thank you for reaching out. This has been noted.

**Comment by FredDominant** [comment]
@djoks closing this out because the issue has been addressed in the latest update here `https://pub.dev/packages/flutterwave/versions/0.0.3-dev.2`
