### ISSUE TITLE
Merchant is not enables for Rave v3

### ISSUE THREAD

**Issue by ICT-VeriTech** [Flutterwave/flutterwave-flutter#35]
After integrating Flutterwave official flutter library in my system everything was fine until when i tried to perform a live transaction, i started getting this error "Merchant is not enables for Rave v3" and I also noticed that the library is returning the card details. 

Please is there a way i can stop the library from returning the card details because i don't actually need those and so that i won't have to submit a PCI DSS.

**Comment by FredDominant** [comment]
Hi @ICT-VeriTech, To use the Flutter SDK, you have to be enabled for V3. And to be enabled for V3, you need to be PCIDSS certified. There's currently no way to stop the library from returning card details.

**Comment by drexhacker** [comment]
@FredDominant And exactly how to be `PCIDSS certified`?
