### ISSUE TITLE
Str.replace is not a function

### ISSUE THREAD

**Issue by Yonkokilasi** [Flutterwave/flutterwave-flutter#36]
When running the Flutterwave.forUIPayment method. When the user enters details for mobile money or card and selects pay, 
I get a toast saying "str.replace is not a function" and then nothing happens. If you click the button it happens again.
If you go back one step and try to pay again , 
` final ChargeResponse response =
              await flutterwave.initializeForUiPayments();`
returns response as null until you restart the application . 
This is my code 
` 
        Flutterwave flutterwave = Flutterwave.forUIPayment(
            context: this.context,
            encryptionKey: secret.secondKey,
            publicKey: secret.firstKey,
            currency: FlutterwaveCurrency.KES,
            amount: "10",
            email: "johndoe@example.com,
            fullName: "name@gmail.com",
            txRef:"lorem ipsum",
            isDebugMode: true,
            phoneNumber: "phone number",
            acceptCardPayment: true,
            acceptUSSDPayment: false,
            acceptAccountPayment: true,
            acceptMpesaPayment: true,
            acceptFrancophoneMobileMoney: false,
            acceptGhanaPayment: false,
            acceptRwandaMoneyPayment: true,
            acceptUgandaPayment: false,
            acceptZambiaPayment: false);
`

**Comment by FredDominant** [comment]
Hello @Yonkokilasi, Thank you for reaching out and apologies for the inconvenience. Does this happen on live or test mode?

**Comment by Yonkokilasi** [comment]
Test mode

**Comment by FredDominant** [comment]
@Yonkokilasi, please share the test card you're using to make the transaction. Also, please note that the method requires Encryption key (not secret key) and public key. These values should be non-null.

**Comment by Yonkokilasi** [comment]
This fails on both card and mpesa payment. The error shows up when you
click the Pay button on whatever payment method. Saw on another issue that
this is a response from an API .
To test you can just set the flutter wave account to test and then use
mpesa and enter any phone number

kind regards,

**Comment by Yonkokilasi** [comment]
see here :
https://developer.flutterwave.com/discuss/5f16383a780c70021fc8d047

**Comment by Yonkokilasi** [comment]
Also , Whenever I pass my details and I get the STK push for MPESA , The
organization that comes up is MWALONI LTD. Then when I proceed, I get
Transaction failed , MPESA cannot complete payment of 'amount' to MWALONI
LTD.ORganisation receiving the payment is unavailable yet I have set up my
organization on my flutter wave account. This is when test mode is off.

**Comment by Yonkokilasi** [comment]
> @Yonkokilasi, please share the test card you're using to make the transaction. Also, please note that the method requires Encryption key (not secret key) and public key. These values should be non-null.

Please note 
`encryptionKey: secret.secondKey, publicKey: secret.firstKey`
are just my local variables , They reference the public key and encryption key

**Comment by FredDominant** [comment]
Hello @Yonkokilasi, thank you for reaching out. 
Please note this is the official library from Flutterwave: `https://pub.dev/packages/flutterwave/`. The versions are 0.0.2 and 0.0.3-dev.1

**Comment by Yonkokilasi** [comment]
> Hello @Yonkokilasi, thank you for reaching out.
> Please note this is the official library from Flutterwave: `https://pub.dev/packages/flutterwave/`. The versions are 0.0.2 and 0.0.3-dev.2

I understand that , but your plugin was not working, however the other plugin was . So I opted for the other as I need to implement Flutter wave

**Comment by Yonkokilasi** [comment]
> Hello @Yonkokilasi, thank you for reaching out.
> Please note this is the official library from Flutterwave: `https://pub.dev/packages/flutterwave/`. The versions are 0.0.2 and 0.0.3-dev.2

The 0.0.3-dev.2 package , clashes with the release version of dio package. Meaning that I am unable to implement the plugin . The issue is that your new plugin uses the new http version. Which dio and many other packages including flutter fire do not. I know this may not seem like your problem as those are external packages. But is there any other way ?
