### ISSUE TITLE
Test card information

### ISSUE THREAD

**Issue by mericgerceker** [Flutterwave/flutterwave-flutter#37]
Hi! I integrate the FlutterWave payment system into an application. I am running it in test mode. I want to pay for testing purposes. With which card number can I do this?

I got an error when I tried it with the cards in the document. https://developer.flutterwave.com/docs/test-cards

**Comment by mericgerceker** [comment]
It worked when I did the debug mode to true. There is no problem right now.

**Comment by pesova** [comment]
> It worked when I did the debug mode to true. There is no problem right now.

hello please how did you resolve this?

**Comment by mericgerceker** [comment]
> hello please how did you resolve this?

Hi! I don't remember how I solved the problem. But I think I set isDebugMode true from Flutterwave.forUIPayment parameters.
