### ISSUE TITLE
Update plugin

### ISSUE THREAD

**Issue by pbwauyo** [Flutterwave/flutterwave-flutter#38]
There are many conflicts with other packages when this plugin is used in a project. This happens especially with the http plugin since this package still depends on an older version of the http plugin(`http: ^0.12.2`) and yet many other plugins depend on the newer http plugin(`http: ^0.13.0` at the moment). The same for the `webview_flutter `plugin. Also it would be good to migrate to null safety.

**Comment by FredDominant** [comment]
Hello @pbwauyo,
Thank you for reaching out. The dependencies have been updated in this version `https://pub.dev/packages/flutterwave/versions/0.0.3-dev.1`
