### ISSUE TITLE
Flutterwave card payments stops at initiating payment

### ISSUE THREAD

**Issue by deut818** [Flutterwave/flutterwave-flutter#41]
final Flutterwave flutterwave = Flutterwave.forUIPayment(
      context: context,
      encryptionKey: _paymentConfig.encKey,
      publicKey: _paymentConfig.publicKey,
      currency: currency,
      amount: amount,
      email: email,
      fullName: fullName,
      txRef: txref + '-C',
      isDebugMode: true,
      phoneNumber: phoneNumber,
      acceptCardPayment: true,
      acceptUSSDPayment: false,
      acceptAccountPayment: false,
      acceptFrancophoneMobileMoney: false,
      acceptGhanaPayment: false,
      acceptMpesaPayment: false,
      acceptRwandaMoneyPayment: false,
      acceptUgandaPayment: false,
      acceptZambiaPayment: false);

**Comment by FredDominant** [comment]
Hello @deut818, apologies for the inconvenience. Please provide details of the test card and currency so we can investigate.

**Comment by deut818** [comment]
Visa 4242424242424242 CVV: 812 01/31 UGX

**Comment by deut818** [comment]
Secondly The charge is actually shown on my account but then for the app after starting initiation process it does not stop

**Comment by FredDominant** [comment]
Hello @deut818, apologies for the inconvenience. This issue has been resolved in this [version](https://pub.dev/packages/flutterwave/versions/0.0.3-dev.2).

**Comment by steph2020-cloud** [comment]
I have a similar problem but in my case i have integrated flutter payment into my project and the payment process fails to call the flutter classes that are required to confirm payment.However, if i test the example code in separate project payment process works accordingly.

**Comment by juniorkibirige** [comment]
Please close the issue if resolved
