### ISSUE TITLE
Implementing checkout with paypal

### ISSUE THREAD

**Issue by Wizpna** [Flutterwave/flutterwave-flutter#42]
Congrats once again to the flutter team.

Our company wants to implement the new feature which involves checking out with paypal.

I will need some guard on how this feature is being implemented using the flutterwave-flutter

Thanks for your response.

**Comment by FredDominant** [comment]
Hello @Wizpna.
Thank you for reaching out. This feature has not been released on the flutter library. Please stay tuned for updates 😁
Thank you for using Flutterwave.
