### ISSUE TITLE
Invalid public key passed

### ISSUE THREAD

**Issue by Rondumel** [Flutterwave/flutterwave-flutter#43]
I keep getting an error, "invalid public key passed". What can I do to solve this please? And if already solved, can you link me to that solution? Thanks

**Comment by FredDominant** [comment]
Hello @Rondumel, please make sure you pass the correct keys for the corresponding environment. if your `isDebugMode` is set to `true`, then you're on test, and should use your test keys. If it's set to `false`, then you should use your live keys, and set your dashboard to live.

**Comment by CharlesTheProgrammerBrown** [comment]
> Hello @Rondumel, please make sure you pass the correct keys for the corresponding environment. if your `isDebugMode` is set to `true`, then you're on test, and should use your test keys. If it's set to `false`, then you should use your live keys, and set your dashboard to live.

@FredDominant I signed up on Flutterwave, and accessed the API tab and copied the public key and encryption key, and I have isDebugMode set to true, but I also get the same error of "invalid public key passed". Please help

**Comment by FredDominant** [comment]
Hello @CharlesTheProgrammerBrown, no it doesn't mean your test was a success. It means a temporary restriction has been placed on your card transactions, so you need to contact `compliance@flutterwavego.com` about the next steps.
