### ISSUE TITLE
Merchant cannot perform transactions without approval.

### ISSUE THREAD

**Issue by steph2020-cloud** [Flutterwave/flutterwave-flutter#44]
How can I resolve this error message ? 

I/flutter (12463): {"status":"error","message":"Merchant cannot perform transactions without approval.","data":null}
I/flutter (12463): RaveResult{status: RaveStatus.error, rawResponse: null, message: Merchant cannot perform transactions without approval.}

**Comment by FredDominant** [comment]
Hello @steph2020-cloud,

Can you confirm you're using the library here => https://pub.dev/packages/flutterwave/versions/0.0.3-dev.2

**Comment by steph2020-cloud** [comment]
Yes im using version 3.I get the message error when i switch currency to South African Rand.But when i test with Nigerian currency transactions goes through without issues.

**Comment by FredDominant** [comment]
Hello @steph2020-cloud, the library doesn't have a version 3.1, so it appears you're not using the official library provided by flutterwave. Therefore we're unable to prove support on such library.

You can get the supported library here https://pub.dev/packages/flutterwave/versions/0.0.3-dev.2

Apologies for the inconvenience.

**Comment by steph2020-cloud** [comment]
Sorry thats a typo i made .I meant 0.0.3 -dev.2 i have this referenced in my Yaml file.

**Comment by FredDominant** [comment]
@steph2020-cloud, please send an email to `compliance@flutterwavego.com`
