### ISSUE TITLE
Signature must contain one of the customer's name

### ISSUE THREAD

**Issue by CharlesTheProgrammerBrown** [Flutterwave/flutterwave-flutter#46]
Hello I ran the example from pubdev for the flutterwave package and I used the access bank test account to open the flutterwave dashboard.

In the flutter UI when I attempt to pay (using Naira currency) if I choose account transfer, I get this error message: "_**Signature must contain one of the customer's name**_" 

If I use card payment, it says "_**Merchant cannot accept international payments at this time. Contact support**_". 

Kindly help with this,

**Comment by FredDominant** [comment]
Hello @CharlesTheProgrammerBrown ,

Please note that `Access Bank` is temporarily disabled for Bank Account payments.
About the international payments error, there's a compliance restriction on card payments. So you need to send an email to `compliance@flutterwavego.com`, where you would be informed of the next steps to have this restriction lifted.
