### ISSUE TITLE
Null Safe Version

### ISSUE THREAD

**Issue by juniorkibirige** [Flutterwave/flutterwave-flutter#47]
Please provide a null safe version for use with flutter 2.0.0, on upgrade null safe is a requisitory

**Comment by juniorkibirige** [comment]
Pull Request #48 is awaiting review and merge

**Comment by juniorkibirige** [comment]
[Migration to Null Safe Implementation](https://github.com/Flutterwave/flutterwave-flutter/pull/48)

**Comment by juniorkibirige** [comment]
@Corvus97 Implementation is completed in PR: #48 
Disturbed UI in Issue: #53 also solved in the same PR

**Comment by FredDominant** [comment]
Closing this because the current version of the library has been fully migrated to null-safety here https://pub.dev/packages/flutterwave.
