### ISSUE TITLE
UI is disturbed in Enter Card details screens

### ISSUE THREAD

**Issue by mianumair91** [Flutterwave/flutterwave-flutter#53]
In pay with card flow, UI is disturbed in iPhone 8 and iPhone 8 Plus
![Simulator Screen Shot - iPhone 8 - 2021-05-25 at 02 28 51](https://user-images.githubusercontent.com/33872147/119410359-2992c180-bd02-11eb-8e65-ef69782d07a0.png)

**Comment by FredDominant** [comment]
Hello @mianumair91, closing this out because it has been fixed in this [version](https://pub.dev/packages/flutterwave/versions/0.0.3-dev.4)
