### ISSUE TITLE
mobile money payment.

### ISSUE THREAD

**Issue by Jules369-ZM** [Flutterwave/flutterwave-flutter#54]
Card payment works just fine....

And mobile money payment  was working just fine but now am not able to make mobile money payment. it just loading meanwhile am able to receive OTP pin on WhatsApp. please i need your help.

**Comment by FredDominant** [comment]
Hello @Jules369-ZM, with what currency does this happen, and is it on staging or live?

**Comment by Jules369-ZM** [comment]
Hello, @FredDominant , the currency is ZMW and am on test environment.

**Comment by FredDominant** [comment]
This is being investigated. Thank you.

**Comment by juniorkibirige** [comment]
@FredDominant Solution exists in PR: #48 
Have a look into it and give feedback
