### ISSUE TITLE
Merchant is not enabled for Rave v3

### ISSUE THREAD

**Issue by budescode** [Flutterwave/flutterwave-flutter#56]
I get this response **"Merchant is not enabled for Rave v3"**
I'm in live mode. Please what should I do?

**Comment by kevinrobert3** [comment]
Did you find a solution for this

**Comment by FredDominant** [comment]
Hello @budescode, @kevinrobert3. Please note that you'll need to be PCI-DSS certified to use the library. Please send an email to compliance@flutterwavego.com
