### ISSUE TITLE
Null safety 

### ISSUE THREAD

**Issue by grey122** [Flutterwave/flutterwave-flutter#57]
Please when is this project going  to be fully migrated to null safety

**Comment by Colin-Stark** [comment]
i also have the same question i really want to use flutterwave but they are pushing me to paystack because their flutter plugin is not null safe

**Comment by kekavc24** [comment]
Starting today. The null safety version was published today.

**Comment by grey122** [comment]
> Starting today. The null safe version was published today.

Thanks very much, this can be closed now
