### ISSUE TITLE
Pay with account not showing

### ISSUE THREAD

**Issue by KelvinForteta** [Flutterwave/flutterwave-flutter#60]
Good day, 
I just integrated the flutterwave plugin to my mobile app and the currency is set to NGN, acceptCardPayment, acceptUSSDPayment, acceptAccountPayment and acceptBankTransfer are all set to true but what is displayed on the flutterwave screen is different from the parameters set. Am I missing something here? Below is the screenshot of what is been displayed on the screen.

[https://i.postimg.cc/brBz81YK/simulator-screenshot-2-A655-E12-FCFD-424-A-A0-D2-F5-A1-B980774-D.png](url)

**Comment by FredDominant** [comment]
Hello @KelvinForteta what version of the library are you using?

**Comment by KelvinForteta** [comment]
0.0.9-alpha+2

**Comment by FredDominant** [comment]
@KelvinForteta, please note this is the official library https://pub.dev/packages/flutterwave

**Comment by KelvinForteta** [comment]
Ok thanks, i guess you guys just updated it to support null safety
