### ISSUE TITLE
Merchant is not enabled for Rave v3

### ISSUE THREAD

**Issue by drexhacker** [Flutterwave/flutterwave-flutter#63]
Hey i receive this error when i try to use card payments.
And in some of the similar issues I saw someone mentioning that you have to be PCIDSS certified to use cards. `so how to be PCIDSS certified?` or `What is PCIDSS certificate?`

**Comment by FredDominant** [comment]
Please send an email to `compliance@flutterwavego.com` or `hi@flutterwavego.com`

**Comment by drexhacker** [comment]
@FredDominant Thanks for the advise.
