### ISSUE TITLE
Could not process Card

### ISSUE THREAD

**Issue by iyinusa** [Flutterwave/flutterwave-flutter#67]
Lovely! Thanks Flutterwave.

Implemented by supplying Test API Public and Encryption Key. After supplying Card Details, clicking on PAY button, it keep returning below error:

"Unable to encrypt request. Please try again"

Please how can this be resolved?

Thanks

**Comment by FredDominant** [comment]
Hello @iyinusa. Please note that this library is no more supported. The more updated library can be found here https://pub.dev/packages/flutterwave_standard

**Comment by iyinusa** [comment]
Thanks. 

And I've used this new package and working well.

Appreciate
