### ISSUE TITLE
USSD payment option not showing

### ISSUE THREAD

**Issue by kevinmisigaro** [Flutterwave/flutterwave-flutter#68]
I am from Tanzania have set acceptUSSDPayment, acceptMPesaPayment for my app but it is only showing Pay with Card option on my app. Most users prefer payment with mobile money. How do i fix? 

<img width="367" alt="Screenshot 2021-09-29 at 14 57 49" src="https://user-images.githubusercontent.com/29556298/135263967-e749747d-1f2d-4227-b364-f903bedd9e06.png">

**Comment by FredDominant** [comment]
Hi @kevinmisigaro, the payment options shown depend on the currency and country set. Only card payment is available on this package for Tanzania. You can check https://pub.dev/packages/flutterwave_standard for more payment options

**Comment by kevinmisigaro** [comment]
okay. moving to that package now. thanks
